version: '3.5'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-2.0
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./ImageProcessor.sln && dotnet publish ./ImageProcessor.sln -c Release -o ./obj/Docker/publish"
